#server:
#  port: 8082
#spring:
#  application:
#    name: activityservice
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/aiactivityfitness
#      database: aiactivityfitness
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  kafka:
#    bootstrap-server: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#kafka:
#  topic:
#    name: activity-events

server:
  port: 8082

spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness

  kafka:
    bootstrap-servers: localhost:9092   # plural: bootstrap-servers
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  # Allow deserialization of all packages

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

kafka:
  topic:
    name: activity-events
