server:
  port: 8083
spring:
  application:
    name: aiservices
  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendationfitness
      database: airecommendationfitness
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
